#!/usr/bin/env python3
"""Build offline shader bytecode using CompileShaderBlob.exe (.cso / legacy .dxbc).

By default CMake passes --built-dir to the per-configuration runtime ShaderLibDX/Built under the build
tree so Debug/Release do not share one source-tree Built/. HLSL inputs always come from --shader-root.

Incremental: skips CompileShaderBlob when the .cso is newer than the manifest, this script,
CompileShaderBlob.exe, and the entry HLSL file plus all reachable quoted #includes.

Lookup hash matches RenderCore::ShaderPrecompileLookupHash: FNV on basename|entry|profile|cpt=tier and macros,
then FNV on quoted-include dependency raw bytes (0x00 between files), then FNV on 8-byte tree hash.

The manifest is generated by Tools/gen_precompile_manifest.py (GLFFViewer/Engine scope; do not hand-edit JSON).
Defines order must match runtime std::vector<RHIShaderMacro> push order for that shader.

Usage:
  python Tools/build_precompiled_shaders.py --compiler path/to/CompileShaderBlob.exe \\
    --manifest Render/ShaderLibDX/precompile_manifest.json \\
    --shader-root Render/ShaderLibDX \\
    --built-dir build/bin/debug/ShaderLibDX/Built

  python Tools/build_precompiled_shaders.py ... --force   # rebuild everything
  python Tools/build_precompiled_shaders.py ... --verbose # print each compile command
  python Tools/build_precompiled_shaders.py ... --no-progress  # only final summary line
  python Tools/build_precompiled_shaders.py ... -j 16      # parallel compile (0 = auto from CPU / env)
  Env MINIENGINE_PRECOMPILE_JOBS: when -j 0, if set to a positive integer, used as worker count (else auto).
  Default tier: 1 (OPT_LEVEL0) unless --compile-tier is set. CMake passes Debug→tier 2, non-Debug→tier 1. --full-opt = tier 0.
  --precompile-config Debug|Release selects Built/.precompile_fxc_tier.<name> (match VS bucket; non-Debug builds use Release).
  Timings: each rebuilt line shows subprocess seconds; final line includes sum of subprocess times and rebuild wall clock.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path

HASH_SEED = 2166136261
MASK64 = (1 << 64) - 1

INCLUDE_QUOTED = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def hash_bytes(data: bytes, result: int) -> int:
    x = result & MASK64
    for b in data:
        x = ((x * 16777619) ^ b) & MASK64
    return x


def hash_string(s: str, result: int) -> int:
    return hash_bytes(s.encode("utf-8"), result)


def dependency_content_hash(entry_hlsl: Path) -> int:
    """Match ShaderPrecompileQuotedIncludeTreeHash: DFS quoted includes, raw bytes + 0x00 delimiter each file."""
    paths = collect_hlsl_sources(entry_hlsl.resolve())
    h = HASH_SEED
    delim = b"\x00"
    for p in paths:
        if not p.is_file():
            continue
        try:
            data = p.read_bytes()
        except OSError:
            continue
        h = hash_bytes(data, h)
        h = hash_bytes(delim, h)
    return h


def lookup_hash(
    filename: str, entry: str, profile: str, defines: list[tuple[str, str]], hlsl_path: Path, compile_tier: str
) -> int:
    h = hash_string(f"{filename}|{entry}|{profile}|cpt={compile_tier}", HASH_SEED)
    for name, val in defines:
        h = hash_string(name, h)
        h = hash_string(val, h)
    tree = dependency_content_hash(hlsl_path)
    return hash_bytes(tree.to_bytes(8, byteorder=sys.byteorder), h)


def hex16(v: int) -> str:
    return f"{v & MASK64:016x}"


def collect_hlsl_sources(entry_hlsl: Path) -> list[Path]:
    """All reachable .hlsl via quoted #includes from entry_hlsl (same-dir relative paths)."""
    entry_hlsl = entry_hlsl.resolve()
    ordered: list[Path] = []
    seen: set[Path] = set()

    def visit(p: Path) -> None:
        p = p.resolve()
        if p in seen:
            return
        seen.add(p)
        ordered.append(p)
        if not p.is_file():
            return
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return
        for line in text.splitlines():
            m = INCLUDE_QUOTED.match(line.strip())
            if not m:
                continue
            child = (p.parent / m.group(1)).resolve()
            if child.is_file():
                visit(child)

    visit(entry_hlsl)
    return ordered


def max_mtime(paths: list[Path]) -> float:
    m = 0.0
    for p in paths:
        if p.is_file():
            m = max(m, p.stat().st_mtime)
    return m


def output_is_stale(out_path: Path, dep_paths: list[Path], force: bool) -> bool:
    if force:
        return True
    if not out_path.is_file():
        return True
    out_t = out_path.stat().st_mtime
    dep_t = max_mtime(dep_paths)
    # Rebuild if any dependency is newer than the output (strict).
    return dep_t > out_t


@dataclass(frozen=True)
class _CompileJob:
    cmd: list[str]
    rel: str
    entry: str
    profile: str
    macros_desc: str
    verbose: bool
    subprocess_env: dict[str, str]


def _default_parallel_jobs() -> int:
    """Parallel FXC processes (one manifest entry each). Cap avoids extreme oversubscription on huge CPU counts."""
    cpu = os.cpu_count() or 4
    return max(1, min(64, cpu))


def _effective_parallel_jobs(cli_jobs: int) -> int:
    if cli_jobs > 0:
        return cli_jobs
    env = os.environ.get("MINIENGINE_PRECOMPILE_JOBS", "").strip()
    if env.isdigit():
        n = int(env)
        if n > 0:
            return max(1, min(256, n))
    return _default_parallel_jobs()


def _run_compile_job(job: _CompileJob, print_lock: threading.Lock, progress: list[int], show_progress: bool) -> tuple[bool, float]:
    if job.verbose:
        with print_lock:
            print(" ".join(job.cmd), flush=True)
    env = os.environ.copy()
    env.update(job.subprocess_env)
    t0 = time.perf_counter()
    r = subprocess.run(job.cmd, shell=False, env=env)
    dt = time.perf_counter() - t0
    ok = r.returncode == 0
    if show_progress:
        with print_lock:
            progress[0] += 1
            n = progress[0]
            tot = progress[1]
            tag = "ok" if ok else "FAIL"
            print(
                f"[precompile] ({n}/{tot}) {tag} {dt:.2f}s  {job.rel} :: {job.entry} [{job.profile}] {job.macros_desc}",
                flush=True,
            )
    return ok, dt


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--compiler", required=True, help="CompileShaderBlob.exe path")
    ap.add_argument("--manifest", required=True, type=Path)
    ap.add_argument("--shader-root", required=True, type=Path)
    ap.add_argument(
        "--built-dir",
        type=Path,
        default=None,
        metavar="DIR",
        help="Output directory for .cso and tier sidecars (default: <shader-root>/Built). CMake passes per-config .../ShaderLibDX/Built.",
    )
    ap.add_argument("--force", action="store_true", help="Ignore timestamps; rebuild all entries")
    ap.add_argument("--verbose", "-v", action="store_true", help="Print CompileShaderBlob command lines")
    ap.add_argument(
        "--no-progress",
        action="store_true",
        help="Do not print per-shader progress (only final rebuilt/skipped/failed summary)",
    )
    ap.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=0,
        metavar="N",
        help="Parallel compile workers (default 0 = auto: env MINIENGINE_PRECOMPILE_JOBS or min(CPU,64)). Use 1 for sequential.",
    )
    ap.add_argument(
        "--full-opt",
        action="store_true",
        help="MINIENGINE_D3DCOMPILE_FAST=0: full FXC optimization; matches Release runtime JIT bytecode (very slow on large PS).",
    )
    ap.add_argument(
        "--hlsl-level0",
        action="store_true",
        help="MINIENGINE_D3DCOMPILE_FAST=1: FXC OPT_LEVEL0 (middle tier).",
    )
    ap.add_argument(
        "--compile-tier",
        choices=("0", "1", "2"),
        default=None,
        help="MINIENGINE_D3DCOMPILE_FAST: 0 full, 1 LEVEL0, 2 SKIP_OPTIMIZATION. Ignored if --full-opt or --hlsl-level0 is set.",
    )
    ap.add_argument(
        "--precompile-config",
        choices=("Debug", "Release"),
        default="Release",
        metavar="NAME",
        help="Writes Built/.precompile_fxc_tier.<NAME> (CMake passes Debug vs Release bucket).",
    )
    args = ap.parse_args()

    compiler = Path(args.compiler).resolve()
    if not compiler.is_file():
        print(f"Compiler not found: {compiler}", file=sys.stderr)
        return 1

    manifest_path = args.manifest.resolve()
    shader_root = args.shader_root.resolve()
    self_script = Path(__file__).resolve()
    built_dir = (args.built_dir.resolve() if args.built_dir else (shader_root / "Built"))

    # utf-8-sig: tolerate UTF-8 BOM (VS / Notepad++ sometimes save manifest with BOM; json.loads rejects raw BOM).
    data = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    shaders = data.get("shaders", [])
    built_dir.mkdir(parents=True, exist_ok=True)

    if args.full_opt and (args.hlsl_level0 or args.compile_tier is not None):
        print("[precompile] error: --full-opt cannot be combined with --hlsl-level0 or --compile-tier", file=sys.stderr)
        return 2
    if args.hlsl_level0 and args.compile_tier is not None:
        print("[precompile] error: --hlsl-level0 cannot be combined with --compile-tier", file=sys.stderr)
        return 2
    if args.full_opt:
        compile_tier = "0"
    elif args.hlsl_level0:
        compile_tier = "1"
    elif args.compile_tier is not None:
        compile_tier = args.compile_tier
    else:
        compile_tier = "1"
    # Only touch the tier sidecar when the tier *changes*. Unconditional write() bumps mtime every build; since
    # tier_sidecar is in every entry's dep_paths, that forced dep_mtime > all .cso and wiped incremental precompile.
    tier_sidecar = built_dir / f".precompile_fxc_tier.{args.precompile_config}"
    try:
        prev = tier_sidecar.read_text(encoding="ascii").strip() if tier_sidecar.is_file() else None
    except OSError:
        prev = None
    if prev != compile_tier:
        tier_sidecar.write_text(compile_tier, encoding="ascii")

    failed = 0
    built = 0
    skipped = 0
    total = len(shaders)
    show_progress = not args.no_progress
    jobs = _effective_parallel_jobs(args.jobs)

    if show_progress and total:
        print(f"[precompile] manifest: {total} shader entries", flush=True)
    if args.full_opt and show_progress:
        print("[precompile] --full-opt: FXC flags=0 (expect very long compiles on DeferredLighting-sized PS)", flush=True)
    elif args.hlsl_level0 and show_progress:
        print("[precompile] --hlsl-level0: FXC OPT_LEVEL0 (tier 1)", flush=True)
    elif show_progress and total:
        print(f"[precompile] HLSL tier {compile_tier} ({tier_sidecar.name})", flush=True)
    compile_child_env = {"MINIENGINE_D3DCOMPILE_FAST": compile_tier}

    to_build: list[_CompileJob] = []

    for item in shaders:
        rel = item["file"]
        entry = item["entry"]
        profile = item["profile"]
        defines_raw = item.get("defines", [])
        defines: list[tuple[str, str]] = []
        for pair in defines_raw:
            if isinstance(pair, list) and len(pair) == 2:
                defines.append((str(pair[0]), str(pair[1])))
            elif isinstance(pair, str) and "=" in pair:
                n, v = pair.split("=", 1)
                defines.append((n, v))
            else:
                print(f"Bad define entry {pair!r} in {rel}", file=sys.stderr)
                failed += 1
                continue

        hlsl_path = (shader_root / rel).resolve()
        base_name = Path(rel).name
        defines_eff = list(defines)
        h = lookup_hash(base_name, entry, profile, defines_eff, hlsl_path, compile_tier)
        out_name = f"{base_name}__{entry}__{profile}__{hex16(h)}.cso"
        out_path = (built_dir / out_name).resolve()
        if not hlsl_path.is_file():
            print(f"Missing HLSL: {hlsl_path}", file=sys.stderr)
            failed += 1
            continue

        hlsl_deps = collect_hlsl_sources(hlsl_path)
        dep_paths = [*hlsl_deps, manifest_path, compiler, self_script, tier_sidecar]

        if not output_is_stale(out_path, dep_paths, args.force):
            skipped += 1
            continue

        cmd = [str(compiler), str(out_path), str(hlsl_path), entry, profile]
        for n, v in defines_eff:
            cmd.append(f"{n}={v}")

        macros = " ".join(f"{n}={v}" for n, v in defines_eff) if defines_eff else "(no defines)"
        to_build.append(
            _CompileJob(
                cmd=cmd,
                rel=rel,
                entry=entry,
                profile=profile,
                macros_desc=macros,
                verbose=args.verbose,
                subprocess_env=compile_child_env,
            )
        )

    n_build = len(to_build)
    sum_subprocess_s = 0.0
    rebuild_wall_s = 0.0
    if n_build:
        workers = max(1, min(jobs, n_build))
        if show_progress:
            mode = "parallel" if workers > 1 else "sequential"
            print(f"[precompile] rebuilding {n_build} shader(s) — {workers} worker(s), {mode}", flush=True)
        print_lock = threading.Lock()
        progress = [0, n_build]
        wall0 = time.perf_counter()
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futs = [pool.submit(_run_compile_job, job, print_lock, progress, show_progress) for job in to_build]
            for fut in futs:
                ok, dt = fut.result()
                sum_subprocess_s += dt
                if ok:
                    built += 1
                else:
                    failed += 1
        rebuild_wall_s = time.perf_counter() - wall0

    timing = ""
    if n_build:
        timing = f" | subprocess {sum_subprocess_s:.1f}s (sum), wall {rebuild_wall_s:.1f}s"
    print(
        f"[precompile] done: {built} rebuilt, {skipped} up-to-date, {failed} failed (of {total} manifest entries){timing}",
        flush=True,
    )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
