#!/usr/bin/env python3
"""Generate Render/ShaderLibDX/precompile_manifest.json from structured Python data.

Scope: **GLFFViewer** (GLFFViewer.exe → Engine + WorldSceneRender / deferred / shadows / IBL / post).
DemoRunner / SoftwareRender / standalone demos are not listed — they JIT-compile any extra shaders locally.

Do not hand-edit the JSON. Macro **push order** must match C++ (hashes + runtime compile).

Simplification model (see *_permutation_axes functions below):
  - Shadow / PBR / translucent permutations are Cartesian products of a few boolean axes.
  - Each axis maps to one or more RHIShaderMacro entries in fixed order (mirroring InitShader / InitResource).

Run: python Tools/gen_precompile_manifest.py  |  CMake target PrecompileMiniEngineShaders (depends from GLFFViewer only; see CMakeLists.txt).
The target then runs Tools/build_precompiled_shaders.py (HLSL/FXC) writing Built/ under the build config output dir; sync_shaderlib_dx excludes source Built/. Debug tier 2, non-Debug tier 1 unless overridden.

C++ sources of truth (Engine paths used by the viewer):
  Shadow, PBR, Fur, translucent, deferred lighting, post (tonemap/bloom/SSR/bloom CS), TAA, SSR, sky/IBL bake,
  procedural sky cube, mips, shadow debug wire, FXAA (optional AA path). Not included: EnvironmentShaders / PostProcessDemo /
  LuquidClass / DownSamplePS / BlurPS-only paths (no GLFFViewer references).

Vertex layout: tangent always on CPU when missing. Skinning uses ID_SKINNING_MATRICES only.

Directional shadow helpers (`ShadowPCSS.hlsl`, `DirectionalShadow.hlsl`, `TranslucentShadowLite.hlsl`, …) are **not**
manifest roots: they are reached only via quoted `#include` from listed files (e.g. `DeferredLighting.hlsl`,
`FurMaterial.hlsl`, `TranslucentPBRForward.hlsl`). `Tools/build_precompiled_shaders.py` walks that include tree for
incremental hashes / rebuilds — no extra manifest rows when those files are added or renamed.

Material shaders (PBR / Fur / translucent PS): manifest lists **both** macro sets — without `RHI_BINDLESS` (D3D11
runtime) and with `RHI_BINDLESS=1` (D3D12 when material `WantsRHIBindless()` is true) — so offline `.cso` can match
either API; macro order matches C++ push order per variant.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "Render/ShaderLibDX/precompile_manifest.json"


def _defs(*pairs: tuple[str, str]) -> list[list[str]]:
    return [list(p) for p in pairs]


def shadow_pass_permutation_axes() -> list[list[list[str]]]:
    """ShadowPS.cpp: optional ID_SKINNING_MATRICES only; alpha clip is runtime via MaterialShaderFlags (no macro)."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        pairs: list[tuple[str, str]] = []
        if skinned:
            pairs.append(("ID_SKINNING_MATRICES", "2"))
        out.append(_defs(*pairs))
    return out


def pbr_material_permutation_axes() -> list[list[list[str]]]:
    """PBRMaterialRender::InitShader: optional ID_SKINNING_MATRICES; optional RHI_BINDLESS (D3D12 only at runtime)."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        for use_bindless in (False, True):
            pairs: list[tuple[str, str]] = []
            if skinned:
                pairs.append(("ID_SKINNING_MATRICES", "2"))
            if use_bindless:
                pairs.append(("RHI_BINDLESS", "1"))
            out.append(_defs(*pairs))
    return out


def fur_material_permutation_axes() -> list[list[list[str]]]:
    """Fur forward: same macro axes as PBRMaterialRender::InitShader (skinning × bindless, matching inner + shell)."""
    return pbr_material_permutation_axes()


def translucent_forward_permutation_axes() -> list[list[list[str]]]:
    """TranslucentPBRForward PS: FilterMacrosTranslucentForwardPS leaves empty (D3D11) or RHI_BINDLESS (D3D12).

    Profile must match runtime: D3D11 always ps_5_0; D3D12 uses ps_5_1 only when RHI_BINDLESS (see D3D12Shaders.cpp).
    Precompiling the empty-macro variant as ps_5_1 would never hit TryLoadPrecompiledShaderBytecode and forces a very slow JIT.
    """
    return [_defs(), _defs(("RHI_BINDLESS", "1"))]


MANIFEST_COMMENT = (
    "AUTO-GENERATED by Tools/gen_precompile_manifest.py — GLFFViewer/Engine scope only; edit script then run "
    "(or build PrecompileMiniEngineShaders). Defines order must match C++ RHIShaderMacro push order."
)


def build_shaders_list() -> list[dict]:
    shaders: list[dict] = []

    shaders.append({"file": "DeferredLighting.hlsl", "entry": "PS_DeferredLighting", "profile": "ps_5_0", "defines": []})

    for defs in translucent_forward_permutation_axes():
        profile = "ps_5_1" if defs else "ps_5_0"
        shaders.append(
            {
                "file": "TranslucentPBRForward.hlsl",
                "entry": "MainPS_TranslucentForward",
                "profile": profile,
                "defines": defs,
            }
        )

    shaders.extend(
        [
            {"file": "PostProcess.hlsl", "entry": "VS_ScreenQuad", "profile": "vs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_Tonemapping", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplyBloom", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplySSR", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_ExtractBloom", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_DownSample", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_UpSample", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_Blur", "profile": "cs_5_0", "defines": []},
            {"file": "SSR.hlsl", "entry": "PS_SSR", "profile": "ps_5_0", "defines": []},
            {"file": "TAACS.hlsl", "entry": "TAA_Main", "profile": "cs_5_0", "defines": []},
            {"file": "TAASharpenerCS.hlsl", "entry": "mainCS", "profile": "cs_5_0", "defines": []},
            {"file": "ClusterLightBuildCS.hlsl", "entry": "MainCS", "profile": "cs_5_0", "defines": []},
            {"file": "SkyLightRenderPass.hlsl", "entry": "VS_SkyFullscreen", "profile": "vs_5_0", "defines": []},
            {"file": "SkyLightRenderPass.hlsl", "entry": "PS", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "VS_SkyCube", "profile": "vs_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenIrradiance", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenPrefiltered", "profile": "ps_5_0", "defines": []},
            {"file": "IBLLongLatToCube.hlsl", "entry": "VS_SkyCube", "profile": "vs_5_0", "defines": []},
            {"file": "IBLLongLatToCube.hlsl", "entry": "PS_LongLatToCube", "profile": "ps_5_0", "defines": []},
            {"file": "SkyAtmosphere.hlsl", "entry": "PS_ProceduralSkyCube", "profile": "ps_5_0", "defines": []},
            {"file": "GenerateMips.hlsl", "entry": "VS_Main_Cube", "profile": "vs_5_0", "defines": []},
            {"file": "GenerateMips.hlsl", "entry": "PS_Main_Cube", "profile": "ps_5_0", "defines": []},
            {"file": "DeferredLighting.hlsl", "entry": "VS_ScreenQuad", "profile": "vs_5_0", "defines": []},
            {"file": "ShadowDebugWire.hlsl", "entry": "VS", "profile": "vs_5_0", "defines": []},
            {"file": "ShadowDebugWire.hlsl", "entry": "PS", "profile": "ps_5_0", "defines": []},
            {"file": "FXAA.xsf", "entry": "FXAA_3_11_PixelShader", "profile": "ps_5_0", "defines": []},
        ]
    )

    for defs in shadow_pass_permutation_axes():
        shaders.append({"file": "ShadowPass-PS.hlsl", "entry": "MainPS", "profile": "ps_5_0", "defines": defs})
        shaders.append({"file": "ShadowPass-VS.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    for defs in pbr_material_permutation_axes():
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainPS", "profile": "ps_5_1", "defines": defs})
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    for defs in fur_material_permutation_axes():
        shaders.append({"file": "FurMaterial.hlsl", "entry": "MainPS", "profile": "ps_5_1", "defines": defs})
        shaders.append({"file": "FurPass-VS.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    return shaders


def build_manifest() -> dict:
    return {"version": 1, "comment": MANIFEST_COMMENT, "shaders": build_shaders_list()}


def write_manifest(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def manifest_semantically_equal_on_disk(path: Path, data: dict) -> bool:
    """Same comparison as --check: skip rewriting when unchanged so mtime does not bust shader incremental builds."""
    if not path.is_file():
        return False
    try:
        existing_text = path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        return json.dumps(existing, sort_keys=True) == json.dumps(data, sort_keys=True)
    except (OSError, json.JSONDecodeError, TypeError):
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", "-o", type=Path, default=DEFAULT_OUT, help="Output JSON path")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if on-disk file differs from generated (CI drift guard)",
    )
    args = ap.parse_args()
    out_path: Path = args.output
    generated = build_manifest()

    if args.check:
        if not out_path.is_file():
            print(f"[gen_precompile_manifest] missing {out_path}", file=sys.stderr)
            return 1
        existing_text = out_path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        if json.dumps(existing, sort_keys=True) != json.dumps(generated, sort_keys=True):
            print(
                "[gen_precompile_manifest] precompile_manifest.json is stale — run:\n"
                f"  python Tools/gen_precompile_manifest.py --output {out_path}",
                file=sys.stderr,
            )
            return 1
        print("[gen_precompile_manifest] OK (manifest matches generator)")
        return 0

    if manifest_semantically_equal_on_disk(out_path, generated):
        print(f"[gen_precompile_manifest] unchanged {out_path} ({len(generated['shaders'])} shaders)")
        return 0
    write_manifest(out_path, generated)
    print(f"[gen_precompile_manifest] wrote {out_path} ({len(generated['shaders'])} shaders)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
