#!/usr/bin/env python3
"""Generate Render/ShaderLibDX/precompile_manifest.json (GLFFViewer scope). Do not edit the JSON by hand.

Run: python Tools/gen_precompile_manifest.py
     or CMake target PrecompileMiniEngineShaders → build_precompiled_shaders.py

Add a shader: append a dict in build_shaders_list() with file, entry, profile, defines.
  defines order must match C++ RHIShaderMacro push order.
  Material PS with bindless: use _ps_profile_for_defs (ps_5_1 if RHI_BINDLESS, else ps_5_0).
  Many variants: add a *_permutation_axes() and loop like shadow_pass / pbr_material.
  #include-only helpers need no manifest row (build script follows includes).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "Render/ShaderLibDX/precompile_manifest.json"


def _defs(*pairs: tuple[str, str]) -> list[list[str]]:
    return [list(p) for p in pairs]


def shadow_pass_permutation_axes() -> list[list[list[str]]]:
    """Skinning on/off (ID_SKINNING_MATRICES)."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        pairs: list[tuple[str, str]] = []
        if skinned:
            pairs.append(("ID_SKINNING_MATRICES", "2"))
        out.append(_defs(*pairs))
    return out


def pbr_material_permutation_axes() -> list[list[list[str]]]:
    """Skinning × RHI_BINDLESS."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        for use_bindless in (False, True):
            pairs: list[tuple[str, str]] = []
            if skinned:
                pairs.append(("ID_SKINNING_MATRICES", "2"))
            if use_bindless:
                pairs.append(("RHI_BINDLESS", "1"))
            out.append(_defs(*pairs))
    return out


def fur_material_permutation_axes() -> list[list[list[str]]]:
    return pbr_material_permutation_axes()


def translucent_forward_permutation_axes() -> list[list[list[str]]]:
    """No macro vs RHI_BINDLESS."""
    return [_defs(), _defs(("RHI_BINDLESS", "1"))]


def _has_bindless(defs: list[list[str]]) -> bool:
    return any(d[0] == "RHI_BINDLESS" for d in defs)


def _ps_profile_for_defs(defs: list[list[str]]) -> str:
    return "ps_5_1" if _has_bindless(defs) else "ps_5_0"


MANIFEST_COMMENT = "AUTO-GENERATED by Tools/gen_precompile_manifest.py — edit script, do not hand-edit JSON."


def build_shaders_list() -> list[dict]:
    shaders: list[dict] = []

    shaders.append({"file": "DeferredLighting.hlsl", "entry": "PS_DeferredLighting", "profile": "ps_5_0", "defines": []})

    for defs in translucent_forward_permutation_axes():
        shaders.append(
            {
                "file": "TranslucentPBRForward.hlsl",
                "entry": "MainPS_TranslucentForward",
                "profile": _ps_profile_for_defs(defs),
                "defines": defs,
            }
        )

    shaders.extend(
        [
            {"file": "PostProcess.hlsl", "entry": "VS_ScreenQuad", "profile": "vs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_Tonemapping", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplyBloom", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplySSR", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_ExtractBloom", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_DownSample", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_UpSample", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_Blur", "profile": "cs_5_0", "defines": []},
            {"file": "SSR.hlsl", "entry": "PS_SSR", "profile": "ps_5_0", "defines": []},
            {"file": "TAACS.hlsl", "entry": "TAA_Main", "profile": "cs_5_0", "defines": []},
            {"file": "TAASharpenerCS.hlsl", "entry": "mainCS", "profile": "cs_5_0", "defines": []},
            {"file": "ClusterLightBuildCS.hlsl", "entry": "MainCS", "profile": "cs_5_0", "defines": []},
            {"file": "SkyLightRenderPass.hlsl", "entry": "VS_SkyFullscreen", "profile": "vs_5_0", "defines": []},
            {"file": "SkyLightRenderPass.hlsl", "entry": "PS", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "VS_SkyCube", "profile": "vs_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenIrradiance", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenPrefiltered", "profile": "ps_5_0", "defines": []},
            {"file": "IBLLongLatToCube.hlsl", "entry": "VS_SkyCube", "profile": "vs_5_0", "defines": []},
            {"file": "IBLLongLatToCube.hlsl", "entry": "PS_LongLatToCube", "profile": "ps_5_0", "defines": []},
            {"file": "SkyAtmosphere.hlsl", "entry": "PS_ProceduralSkyCube", "profile": "ps_5_0", "defines": []},
            {"file": "GenerateMips.hlsl", "entry": "VS_Main_Cube", "profile": "vs_5_0", "defines": []},
            {"file": "GenerateMips.hlsl", "entry": "PS_Main_Cube", "profile": "ps_5_0", "defines": []},
            {"file": "DeferredLighting.hlsl", "entry": "VS_ScreenQuad", "profile": "vs_5_0", "defines": []},
            {"file": "ShadowDebugWire.hlsl", "entry": "VS", "profile": "vs_5_0", "defines": []},
            {"file": "ShadowDebugWire.hlsl", "entry": "PS", "profile": "ps_5_0", "defines": []},
            {"file": "FXAA.xsf", "entry": "FXAA_3_11_PixelShader", "profile": "ps_5_0", "defines": []},
        ]
    )

    for defs in shadow_pass_permutation_axes():
        shaders.append({"file": "ShadowPass-PS.hlsl", "entry": "MainPS", "profile": "ps_5_0", "defines": defs})
        shaders.append({"file": "ShadowPass-VS.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    for defs in pbr_material_permutation_axes():
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainPS", "profile": _ps_profile_for_defs(defs), "defines": defs})
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    for defs in fur_material_permutation_axes():
        shaders.append({"file": "FurMaterial.hlsl", "entry": "MainPS", "profile": _ps_profile_for_defs(defs), "defines": defs})
        shaders.append({"file": "FurPass-VS.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    return shaders


def build_manifest() -> dict:
    return {"version": 1, "comment": MANIFEST_COMMENT, "shaders": build_shaders_list()}


def write_manifest(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def manifest_semantically_equal_on_disk(path: Path, data: dict) -> bool:
    """Skip write when unchanged (preserve mtime for incremental shader builds)."""
    if not path.is_file():
        return False
    try:
        existing_text = path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        return json.dumps(existing, sort_keys=True) == json.dumps(data, sort_keys=True)
    except (OSError, json.JSONDecodeError, TypeError):
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", "-o", type=Path, default=DEFAULT_OUT, help="Output JSON path")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if on-disk file differs from generated (CI drift guard)",
    )
    args = ap.parse_args()
    out_path: Path = args.output
    generated = build_manifest()

    if args.check:
        if not out_path.is_file():
            print(f"[gen_precompile_manifest] missing {out_path}", file=sys.stderr)
            return 1
        existing_text = out_path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        if json.dumps(existing, sort_keys=True) != json.dumps(generated, sort_keys=True):
            print(
                "[gen_precompile_manifest] precompile_manifest.json is stale — run:\n"
                f"  python Tools/gen_precompile_manifest.py --output {out_path}",
                file=sys.stderr,
            )
            return 1
        print("[gen_precompile_manifest] OK (manifest matches generator)")
        return 0

    if manifest_semantically_equal_on_disk(out_path, generated):
        print(f"[gen_precompile_manifest] unchanged {out_path} ({len(generated['shaders'])} shaders)")
        return 0
    write_manifest(out_path, generated)
    print(f"[gen_precompile_manifest] wrote {out_path} ({len(generated['shaders'])} shaders)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
