#!/usr/bin/env python3
"""Generate Render/ShaderLibDX/precompile_manifest.json from structured Python data.

Do not hand-edit the JSON. Macro **push order** must match C++ (hashes + runtime compile).

Simplification model (see *_permutation_axes functions below):
  - Shadow / PBR / translucent permutations are Cartesian products of a few boolean axes.
  - Each axis maps to one or more RHIShaderMacro entries in fixed order (mirroring InitShader / InitResource).
  - Adding a new axis = one new loop + append rules — no hand-maintained 16-row tables.

Run: python Tools/gen_precompile_manifest.py  |  CMake target PrecompileMiniEngineShaders

C++ sources of truth:
  Shadow:          Engine/Src/Engine/Render/Shadow/ShadowPS.cpp InitResource
  PBR base pass:   Engine/Src/Engine/Render/PBRMaterialRender.cpp InitShader
  Translucent PS:  PBRMaterialRender.cpp FilterMacrosTranslucentForwardPS (subset; order preserved here)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "Render/ShaderLibDX/precompile_manifest.json"


def _defs(*pairs: tuple[str, str]) -> list[list[str]]:
    return [list(p) for p in pairs]


def shadow_pass_permutation_axes() -> list[list[list[str]]]:
    """ShadowPS.cpp push order: ID_SKINNING → HAS_TANGENT → HAS_WEIGHTS_0 → SHADOW_ALPHA_CLIP."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        for tangent in (False, True):
            for alpha_clip in (False, True):
                pairs: list[tuple[str, str]] = []
                if skinned:
                    pairs.append(("ID_SKINNING_MATRICES", "2"))
                if tangent:
                    pairs.append(("HAS_TANGENT", "1"))
                if skinned:
                    pairs.append(("HAS_WEIGHTS_0", "1"))
                if alpha_clip:
                    pairs.append(("SHADOW_ALPHA_CLIP", "1"))
                out.append(_defs(*pairs))
    return out


def pbr_material_permutation_axes() -> list[list[list[str]]]:
    """PBRMaterialRender::InitShader push order (before AddShaderMacro): skin block → tangent → weights →
    WRITE_BASECOLOR_ALPHA_TO_GBUFFER → MATERIAL_DOUBLE_SIDED → RHI_BINDLESS."""
    out: list[list[list[str]]] = []
    for skinned in (False, True):
        for tangent in (False, True):
            for write_alpha in (False, True):
                for double_sided in (False, True):
                    pairs: list[tuple[str, str]] = []
                    if skinned:
                        pairs.append(("ID_SKINNING_MATRICES", "2"))
                    if tangent:
                        pairs.append(("HAS_TANGENT", "1"))
                    if skinned:
                        pairs.append(("HAS_WEIGHTS_0", "1"))
                    if write_alpha:
                        pairs.append(("WRITE_BASECOLOR_ALPHA_TO_GBUFFER", "1"))
                    if double_sided:
                        pairs.append(("MATERIAL_DOUBLE_SIDED", "1"))
                    pairs.append(("RHI_BINDLESS", "1"))
                    out.append(_defs(*pairs))
    return out


def translucent_forward_permutation_axes() -> list[list[list[str]]]:
    """Translucent forward PS macros after FilterMacros…: HAS_TANGENT → MATERIAL_DOUBLE_SIDED → RHI_BINDLESS."""
    out: list[list[list[str]]] = []
    for tangent in (False, True):
        for double_sided in (False, True):
            pairs: list[tuple[str, str]] = []
            if tangent:
                pairs.append(("HAS_TANGENT", "1"))
            if double_sided:
                pairs.append(("MATERIAL_DOUBLE_SIDED", "1"))
            pairs.append(("RHI_BINDLESS", "1"))
            out.append(_defs(*pairs))
    return out


MANIFEST_COMMENT = (
    "AUTO-GENERATED by Tools/gen_precompile_manifest.py — edit that script, then run it "
    "(or build PrecompileMiniEngineShaders). Defines order must match C++ RHIShaderMacro push order."
)


def build_shaders_list() -> list[dict]:
    shaders: list[dict] = []

    shaders.append({"file": "DeferredLighting.hlsl", "entry": "PS_DeferredLighting", "profile": "ps_5_0", "defines": []})

    for defs in translucent_forward_permutation_axes():
        shaders.append(
            {
                "file": "TranslucentPBRForward.hlsl",
                "entry": "MainPS_TranslucentForward",
                "profile": "ps_5_1",
                "defines": defs,
            }
        )

    shaders.extend(
        [
            {"file": "PostProcess.hlsl", "entry": "PS_Tonemapping", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplyBloom", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "PS_ApplySSR", "profile": "ps_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_ExtractBloom", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_DownSample", "profile": "cs_5_0", "defines": []},
            {"file": "PostProcess.hlsl", "entry": "CS_UpSample", "profile": "cs_5_0", "defines": []},
            {"file": "SSR.hlsl", "entry": "PS_SSR", "profile": "ps_5_0", "defines": []},
            {"file": "TAACS.hlsl", "entry": "TAA_Main", "profile": "cs_5_0", "defines": []},
            {"file": "TAASharpenerCS.hlsl", "entry": "mainCS", "profile": "cs_5_0", "defines": []},
            {"file": "SkyLightRenderPass.hlsl", "entry": "PS", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenIrradiance", "profile": "ps_5_0", "defines": []},
            {"file": "EnvironmentSkyIBL.hlsl", "entry": "PS_GenPrefiltered", "profile": "ps_5_0", "defines": []},
            {"file": "IBLLongLatToCube.hlsl", "entry": "PS_LongLatToCube", "profile": "ps_5_0", "defines": []},
            {"file": "SkyAtmosphere.hlsl", "entry": "PS_ProceduralSkyCube", "profile": "ps_5_0", "defines": []},
            {"file": "GenerateMips.hlsl", "entry": "PS_Main_Cube", "profile": "ps_5_0", "defines": []},
        ]
    )

    for defs in shadow_pass_permutation_axes():
        shaders.append({"file": "ShadowPass-PS.hlsl", "entry": "MainPS", "profile": "ps_5_0", "defines": defs})
        shaders.append({"file": "ShadowPass-VS.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    for defs in pbr_material_permutation_axes():
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainPS", "profile": "ps_5_1", "defines": defs})
        shaders.append({"file": "PBRMaterial.hlsl", "entry": "MainVS", "profile": "vs_5_0", "defines": defs})

    return shaders


def build_manifest() -> dict:
    return {"version": 1, "comment": MANIFEST_COMMENT, "shaders": build_shaders_list()}


def write_manifest(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def manifest_semantically_equal_on_disk(path: Path, data: dict) -> bool:
    """Same comparison as --check: skip rewriting when unchanged so mtime does not bust shader incremental builds."""
    if not path.is_file():
        return False
    try:
        existing_text = path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        return json.dumps(existing, sort_keys=True) == json.dumps(data, sort_keys=True)
    except (OSError, json.JSONDecodeError, TypeError):
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", "-o", type=Path, default=DEFAULT_OUT, help="Output JSON path")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if on-disk file differs from generated (CI drift guard)",
    )
    args = ap.parse_args()
    out_path: Path = args.output
    generated = build_manifest()

    if args.check:
        if not out_path.is_file():
            print(f"[gen_precompile_manifest] missing {out_path}", file=sys.stderr)
            return 1
        existing_text = out_path.read_text(encoding="utf-8-sig")
        existing = json.loads(existing_text)
        if json.dumps(existing, sort_keys=True) != json.dumps(generated, sort_keys=True):
            print(
                "[gen_precompile_manifest] precompile_manifest.json is stale — run:\n"
                f"  python Tools/gen_precompile_manifest.py --output {out_path}",
                file=sys.stderr,
            )
            return 1
        print("[gen_precompile_manifest] OK (manifest matches generator)")
        return 0

    if manifest_semantically_equal_on_disk(out_path, generated):
        print(f"[gen_precompile_manifest] unchanged {out_path} ({len(generated['shaders'])} shaders)")
        return 0
    write_manifest(out_path, generated)
    print(f"[gen_precompile_manifest] wrote {out_path} ({len(generated['shaders'])} shaders)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
